#!/bin/bash
BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$BRANCH" = "submission" ];
then
  git pull -X theirs origin submission
else
  echo $(tput setaf 1)you must be on the submission branch$(tput sgr0)
fi;
